services:
  - type: web
    name: ic-hdl-generator
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt && pip install gunicorn && python seed_db.py"
    startCommand: "cd backend && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
